name: Firebase Hosting Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: firebaseDB

      - name: Lint Code
        run: npm run lint
        working-directory: firebaseDB

      - name: Build Project
        run: npm run build
        working-directory: firebaseDB

      - name: Sync Files to Dropbox
        run: python sync_to_dropbox.py
        env:
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
        working-directory: firebaseDB

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        working-directory: firebaseDB